### ISSUE TITLE
Show data in graphs only for days past

### ISSUE THREAD

**Issue by 314159265359879** [sigle/stxstats#11]
The graph shows a drop because the unfinished days are included. only show days in the past instead or people my think something is wrong. 
![image](https://user-images.githubusercontent.com/33360391/125745557-b70fbf96-651c-4fa2-b42f-a746a5e1e1e9.png)

![image](https://user-images.githubusercontent.com/33360391/125745646-326e2124-2754-4261-b28c-81531b836191.png)

**Comment by pradel** [comment]
Good idea!

**Comment by pradel** [comment]
After taking a look this was caused by our node being out of sync at this point so shouldn't be a problem forward anymore, thanks for reporting!
