### ISSUE TITLE
Choppy graph on number of transactions

### ISSUE THREAD

**Issue by 314159265359879** [sigle/stxstats#39]
![image](https://user-images.githubusercontent.com/33360391/129982547-92c77494-8df0-4e40-9ab7-750a5785a692.png)

it is actually showing two datapoints for some days here. _August 15th 46 transactions_ and _August 16th 1039 transactions_ I think you meant to show just the one?

**Comment by pradel** [comment]
Thanks for the report, the bug has been fixed and will be resolved as soon as our node catchup :)

**Comment by pradel** [comment]
Fix is live ;)
