### ISSUE TITLE
Site not updating?: december 8 showing 0 transactions

### ISSUE THREAD

**Issue by 314159265359879** [sigle/stxstats#61]
Related to the 2.0.5.0.0.0 upgrade on the 7th?

![image](https://user-images.githubusercontent.com/33360391/145422919-2e244e86-0a26-429d-a73e-15fa767c4d61.png)

**Comment by pradel** [comment]
Yes our node is still running the old stacks node version and is now out of sync, https://twitter.com/sigleapp/status/1468899340831932418.

Working on it to setup a new server!

**Comment by pradel** [comment]
Should be good now
