### ISSUE TITLE
Redesign dashboard page

### ISSUE THREAD

**Issue by pradel** [sigle/stxstats#69]
![Capture d’écran 2022-01-11 à 18 17 54](https://user-images.githubusercontent.com/5749437/148990310-fadd5a18-f4d0-4e86-9652-f8a3cf499f15.png)

**Comment by gregogun** [comment]
Just a couple of questions regarding the redesign:

1. Do we have somewhere to link the nav items yet?

2. I guess this is linked with the first question but is the navigation all happening within the same page (dashboard.tsx) - if so, do you think it would be beneficial at all to use Tabs for switching between content? (I've currently just implemented them as static links to focus on styling, so can adapt them to Tabs if needed)

3. It seems that https://api.stxstats.co/dashboard doesn't return the following data:
    - BTC price
    - STX price
    - 24hr volume
    - Market cap (fully diluted)
  
 Do you know where I could get the remaining data from?
 
 Thanks!

**Comment by pradel** [comment]
1. Not for now you can leave the href property to an empty page for now.
2. It won't be rendered on the same page but on a separate one :)
3. All the price data can be found in the coingecko API https://www.coingecko.com/en/api
